# Generated by Django 5.1.1 on 2024-09-12 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('0 to 10000', '0 to 10000'), ('10000 to 20000', '10000 to 20000'), ('20000 to 30000', '20000 to 30000'), ('30000 to 40000', '30000 to 40000')], max_length=200)),
                ('slug', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('specification', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('label', models.CharField(choices=[('new', 'New'), ('hot', 'Hot'), ('', 'default')], max_length=200)),
                ('stock', models.CharField(choices=[('INSTOCK', 'INSTOCK'), ('OUTSTOCK', 'OUTSTOCK')], max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colour')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.filter_price')),
            ],
        ),
    ]
