# Generated by Django 5.1.1 on 2024-09-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
