# Generated by Django 5.1.1 on 2024-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
